### ISSUE TITLE
Laravel 5.2 Support

### ISSUE THREAD

**Issue by JPT62089** [davispeixoto/Laravel-5-Salesforce#3] opened 2015-12-23 01:03 UTC
Hello!

Any ETA on Laravel 5.2 support? I'm eager to update to 5.2 though laravel/framework requires vlucas/phpdotenv ~2.0 and davispeixoto/laravel5-salesforce requires ~1.0 causing a conflict that Composer doesn't like :P

Thanks!

**Comment by davispeixoto** [comment] 2015-12-23 10:56
Not really, and I wasn't aware of this incompatibility (as I'm not working with Salesforce in my daily routine)

**Comment by hcpunk** [comment] 2016-02-14 23:01
Bitten by the Laravel 5.2 dependency conflict too. Is there no hope of a fix?

**Comment by JPT62089** [comment] 2016-02-15 03:11
Nothing official from davispeixoto, but I did create a [fork](https://github.com/JPT62089/laravel5-salesforce) with just a simple dependency change. No major testing done, but it seems to work for my purposes.

You can use my fork by adding the following to your composer.json file above require

`
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/JPT62089/laravel5-salesforce"
    }
],
`

**Comment by davispeixoto** [comment] 2016-02-15 12:21
Sorry for the delay on replying, guys.

@JPT62089 , can you send a pull request so I can merge it? I've been really, really busy being a manager into a new company.

**Comment by JPT62089** [comment] 2016-02-15 15:52
@davispeixoto, I don't seem to have gotten it, unfortunately. I will say I've done very little testing to make sure it didn't break anything. (All that changed was the phpdotenv version requirements)

Congrats on the new manager job!

**Comment by MarcusFulbright** [comment] 2016-05-26 08:05
To shed some light on this, the problem is fixed in the dev-master branch. So you _can_ `composer require davispeixoto/laravel5-salesforce dev-master`. However, it would be nice if @davispeixoto issued a 1.5 release with the change in it.

**Comment by kryptonalegarme** [comment] 2016-08-04 03:01
Thanks for this, i spent  4 hours to figure out why is not installing, glad i see this comments. :)

**Comment by davispeixoto** [comment] 2016-08-11 21:45
Published

**Closed as completed by davispeixoto** 2016-08-11 21:45 UTC

**Comment by kryptonalegarme** [comment] 2016-08-12 15:58
Hi After I ran composer update, This is the error that I get.

FatalErrorException in SalesforceServiceProvider.php line 53:
Cannot redeclare non static Illuminate\Support\ServiceProvider::$defer as static Davispeixoto\Laravel5Salesforce\SalesforceServiceProvider::$defer

Any thoughts what is problem?

**Comment by davispeixoto** [comment] 2016-08-12 16:17
Probably a fix for an application architecture flaw I've done wrong.

Just fixed and pushed
